version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:6.2-alpine

  worker:
    build: .
    command: celery -A studiohub worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  beat:
    build: .
    command: celery -A studiohub beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data:
