services:
  - type: web
    name: studiohub-web
    env: python
    python-version: 3.11.4
    pip-version: 23.1.2
    buildCommand: "./build.sh"
    startCommand: "gunicorn studiohub.wsgi:application"
    releaseCommand: "python manage.py migrate"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: studiohub-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: studiohub-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CELERY_BROKER_URL
        value: redis://studiohub-redis:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://studiohub-redis:6379/0
      - key: WEB_CONCURRENCY
        value: 8
      - key: PIP_INDEX_URL
        value: https://pypi.org/simple

  - type: worker
    name: studiohub-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A studiohub worker -l info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: studiohub-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: studiohub-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CELERY_BROKER_URL
        value: redis://studiohub-redis:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://studiohub-redis:6379/0

  - type: worker
    name: studiohub-beat
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A studiohub beat -l info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: studiohub-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: studiohub-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CELERY_BROKER_URL
        value: redis://studiohub-redis:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://studiohub-redis:6379/0

  - type: redis
    name: studiohub-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Allow all traffic"

databases:
  - name: studiohub-db
    databaseName: studiohub
    user: studiohub
